version: '3.7'

services:
  hsn_nginx:
    build:
      context: .nginx/
      dockerfile: Dockerfile
    container_name: hsn_nginx
    ports:
      - "1111:1111"
    restart: on-failure
    networks:
      - hsn_network

  hsn_api:
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    container_name: hsn_api
    hostname: hsn_api
    command: uvicorn api.api_server:app --host 0.0.0.0 --port 9999 --reload
    tty: true
    restart: always
    ports:
      - "9999:9999"
    environment:
      DEBUG: '${DEBUG}'
    networks:
      - hsn_network
    depends_on:
      - database
    volumes:
      - '.:/app'

  hsn_admin:
    build:
      context: hsn_admin/
      dockerfile: ../.docker/admin/Dockerfile
    container_name: hsn_admin
    hostname: hsn_api
    networks:
      - hsn_network
    depends_on:
      - hsn_api
    restart: always
    volumes:
      - "./hsn_admin:/admin"
      - "/admin/node_modules"

  database:
    image: postgres
    container_name: database
    hostname: database
    tty: true
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 3s
      retries: 40
    networks:
      - hsn_network


networks:
  hsn_network:
    driver: 'bridge'

volumes:
  db-data:
    name: db-data
  pg-data:
    name: pg-data
