version: '3.7'

services:
  hsn_api:
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    container_name: hsn_api
    hostname: hsn_api
    command: uvicorn api.api_server:app --host 0.0.0.0 --port 9999 --reload
    ports:
      - '9999:9999'
    tty: true
    environment:
      DEBUG: '${DEBUG}'
    networks:
      - backend
    depends_on:
      - database
    volumes:
      - '.:/app'

  database:
    image: postgres
    container_name: database
    hostname: database
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout:  3s
      retries: 40
    networks:
      - backend


networks:
  backend:
    driver: 'bridge'

volumes:
  db-data:
    name: db-data