version: '3.7'

services:
  pg_admin:
    container_name: "pg_admin"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pg-data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    networks:
      - backend

  hsn_api:
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    container_name: hsn_api
    hostname: hsn_api
    command: uvicorn api.api_server:app --host 0.0.0.0 --port 9999 --reload
    ports:
      - '9999:9999'
    tty: true
    restart: always
    environment:
      DEBUG: '${DEBUG}'
    networks:
      - backend
    depends_on:
      - database
    volumes:
      - '.:/app'

  hsn_admin:
    build:
      context: hsn_admin/
      dockerfile: ../.docker/admin/Dockerfile
    container_name: hsn_admin
    hostname: hsn_api
    ports:
      - "5174:5173"
    networks:
      - backend
    depends_on:
      - hsn_api
    restart: always
    volumes:
      - "./hsn_admin:/admin"
      - "/admin/node_modules"

  database:
    image: postgres
    container_name: database
    hostname: database
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 3s
      retries: 40
    networks:
      - backend


networks:
  backend:
    driver: 'bridge'

volumes:
  db-data:
    name: db-data
  pg-data:
    name: pg-data
